import React, { forwardRef } from 'react';

interface PlannerProps {
  data: any;
}

export const AcademicPlannerPDF = forwardRef<HTMLDivElement, PlannerProps>(({ data }, ref) => {
  const { courses, timeline } = data || {};

  return (
    <div
      ref={ref}
      style={{
        width: '794px', // A4 width at 96 DPI
        minHeight: '1123px', // A4 height at 96 DPI
        padding: '40px',
        backgroundColor: '#FFFFFF',
        color: '#0F172A',
        fontFamily: 'Inter, sans-serif',
        display: 'flex',
        flexDirection: 'column',
        gap: '40px',
      }}
    >
      {/* Cover Page */}
      <div style={{ textAlign: 'center', marginTop: '100px', marginBottom: '100px' }}>
        <h1 style={{ fontSize: '3rem', fontWeight: 800, color: '#0F4C3A', marginBottom: '20px' }}>
          Academic Planner
        </h1>
        <p style={{ fontSize: '1.2rem', color: '#6B7280' }}>
          Generated by SyllabusSprint AI
        </p>
        <div style={{ marginTop: '40px', fontSize: '1.1rem', color: '#334155' }}>
          <strong>Semester Overview</strong>
          <p>Total Courses: {courses?.length || 0}</p>
        </div>
      </div>

      {/* Courses Overview */}
      <div>
        <h2 style={{ fontSize: '1.8rem', color: '#1E7B45', borderBottom: '2px solid #E5E7EB', paddingBottom: '10px' }}>
          Your Courses
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginTop: '20px' }}>
          {courses?.map((course: any) => (
            <div key={course.id} style={{ padding: '20px', backgroundColor: '#F8FAFC', borderRadius: '12px', border: '1px solid #E5E7EB' }}>
              <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: '#0F172A' }}>{course.name}</h3>
              <p style={{ fontSize: '0.9rem', color: '#6B7280', marginTop: '8px' }}>
                {course.assignments?.length || 0} Assignments | {course.exams?.length || 0} Exams
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Upcoming Deadlines (Timeline) */}
      <div style={{ pageBreakBefore: 'always' }}>
        <h2 style={{ fontSize: '1.8rem', color: '#1E7B45', borderBottom: '2px solid #E5E7EB', paddingBottom: '10px' }}>
          Timeline & Deadlines
        </h2>
        <div style={{ marginTop: '20px', display: 'flex', flexDirection: 'column', gap: '15px' }}>
          {timeline?.map((item: any) => (
            <div key={item.id} style={{ display: 'flex', gap: '20px', alignItems: 'center', padding: '15px', border: '1px solid #E5E7EB', borderRadius: '8px' }}>
              <div style={{ minWidth: '100px', fontWeight: 600, color: '#1E7B45' }}>
                {new Date(item.date).toLocaleDateString()}
              </div>
              <div>
                <div style={{ fontWeight: 600, color: '#0F172A' }}>{item.title}</div>
                <div style={{ fontSize: '0.9rem', color: '#6B7280' }}>{item.type}</div>
              </div>
            </div>
          ))}
          {(!timeline || timeline.length === 0) && (
            <p style={{ color: '#6B7280' }}>No upcoming deadlines found.</p>
          )}
        </div>
      </div>

    </div>
  );
});

AcademicPlannerPDF.displayName = 'AcademicPlannerPDF';
